@host=https://localhost:7171

POST {{host}}/auth/register
Content-Type: application/json

{
	"firstName": "Alex",
    "lastName" : "Mason",
    "email": "alexBlkwood@email.com",
    "password": "WoodTheDark_235"
}